- name: Amazon EC2 | Create Key Pair
  amazon.aws.ec2_key:
    name: "{{ key_name }}"
    region: "{{ region }}"
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    key_material: "{{ item }}"
  with_file: /home/sailor/.ssh/{{ key_name }}.pub
