# AWS playbook
---
- name: Provisioning EC2 instances
  hosts: localhost
  connection: local
  gather_facts: False

  roles:
    # - create-security-group
    - aws-instance-create/ssh-key-pair
    - aws-instance-create/create-ec2-instance
    - aws-instance-create/instance-facts
