---
- name: Install Laravel 11 on VM
  hosts: all
  become: true

  roles:
    - server-config/common
    - server-config/mysql
    - server-config/firewall
    - server-config/php
    - server-config/composer
    - server-config/project
    - server-config/apache
