- name: Create security group
  amazon.aws.ec2_security_group:
    name: "{{ sec_group }}"
    description: "Sec group for app"
    region: "{{ region }}"
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    rules:
      - proto: tcp
        ports:
          - 22
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all on ssh port
