#repo clone
- name: Clone  github repository
  git:
    repo: https://github.com/sagor-roy/billionairecars-dynamic.git
    dest: /var/www/{{ project_name }}
    clone: yes
    update: no

#file permission
- name: Change ownership of project directory
  ansible.builtin.file:
    path: /var/www/{{ project_name }}
    owner: www-data
    group: www-data
    recurse: yes

- name: Ensure storage and bootstrap/cache directories are writable
  file:
    path: "/var/www/{{ project_name }}/{{ item }}"
    mode: "0777"
    owner: www-data
    group: www-data
    recurse: yes
  loop:
    - storage
    - bootstrap/cache

- name: Modify .env file
  template: src=.env  dest="/var/www/{{ project_name }}/.env" owner=www-data mode=0644

# Install Laravel dependencies
- name: Install Composer dependencies
  shell: composer install --no-interaction
  args:
    chdir: /var/www/{{ project_name }}
